language: ruby
rvm:
  - 1.9.3

env:
  - SCRIPTS="rake test --trace TESTOPTS='-v'"
  - SCRIPTS="rspec spec --color"

script:
  - bundle exec $SCRIPTS

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:load

notifications:
  email:
    - alex.mehovov@gmail.com
    - mark-k@ukr.net
